import "../globals.css";
import type { Metadata } from "next";
import Sidebar from "../_shared/components/sidebar";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased flex gap-6 w-screen`}
            >
                <div className="flex min-h-screen items-center justify-center bg-zinc-50 font-sans">
                    <Sidebar/>
                </div>
                <div className="w-full h-[97vh] my-2 mr-3 rounded-md px-3 py-2 shadow-xl relative">
                    {children}
                </div>
            </body>
        </html>
    );
}
